future: true
permalink: /:title/
url: http://gaoynui.github.io
name: GaoYang
author: GaoYang
qq: 374441211
email: gaoy_1@outlook.com
weChat: listen5240
github: gaoynui

about: "这里是高阳的个人博客，创建于2018.03年。"

safe: true
paginate: 20
