future: true
permalink: /:title/
url: http://gaoynui.github.io
name: Gao Yang
author: gy
qq: 374441211
email: gaoy_1@outlook.com

duoshuo: 
beian: 
cnzz: 
weibo: 
github: gaoynui
about: "这里是高阳的个人博客，创建于2018年。"

safe: true
paginate: 20

